namespace Parsing.AbstractSyntaxTree.Expressions
{
    public enum ExpressionType
    {
        DontCare = -1,
        Add,
        AddAssign,
        Subtract,
        SubtractAssign,
        Multiply,
        MultiplyAssign,
        Divide,
        DivideAssign,
        Modulo,
        ModuloAssign,
        LessThan,
        LessThanEqual,
        FunctionCall,
        Identifier,
        GreaterThan,
        GreaterThanEqual,
        Equivalent,
        Equals,
        NotEquivalent,
        NotEquals,
        BitShiftLeft,
        BitShiftRight,
        Value,
        Assignment,
        Body,
        IfStatementExpression,
        ForStatementExpression,
        WhileStatementExpression,
        DoWhileStatementExpression,
        ConditionalOr,
        ConditionalXOr,
        ConditionalAnd,
        BitwiseOr,
        BitwiseAnd,
        FunctionDefinition,
        VariableDeclaration,
        Return,
        NegativeValue,
    }

}
